### ISSUE TITLE
[Mohist 1.16.5] "Could not load"

### ISSUE THREAD

**Issue by MasterXort** [promcteam/promccore#12]
That's the problem. I'm new to setting up plugins, I don't understand what's going on.

```java
[22:07:49 ERROR]: Could not load 'plugins/ProMCCore-v1.0.4-R0.2-20221217.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: mc/promcteam/engine/NexEngine has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:390) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:922) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.Bukkit.reload(Bukkit.java:637) ~[forge:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:171) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:775) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:759) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:367) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:339) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1003) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.lang.UnsupportedClassVersionError: mc/promcteam/engine/NexEngine has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_301]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_301]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:176) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:116) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:111) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_301]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[forge:?]
        ... 15 more
```

**Comment by Travja** [comment]
Ah. I compiled it against Java 11. I can adjust that, to compile against Java 8, or you can upgrade to 11. You should be able to run 1.16 with 11 just fine

**Comment by MasterXort** [comment]
> Ah. I compiled it against Java 11. I can adjust that, to compile against Java 8, or you can upgrade to 11. You should be able to run 1.16 with 11 just fine

I changed it. Oh, it works! Thank you very much)
